import { describe, it, expect } from 'vitest';
import { stripForLlm } from '../src/export/llm.js';

describe('stripForLlm', () => {
  it('strips frontmatter, comments, banner, and extra blanks', () => {
    const input = [
      '---',
      'title: x',
      '---',
      '<!-- AUTO-GENERATED by mdcp -->',
      '<!-- note -->',
      '',
      '# Title',
      '',
      '',
      'Body.',
      '',
    ].join('\n');

    const out = stripForLlm(input);
    expect(out).not.toContain('---');
    expect(out).not.toContain('AUTO-GENERATED');
    expect(out).not.toContain('<!--');
    expect(out).toContain('# Title');
    expect(out).toContain('Body.');
    expect(out).not.toMatch(/\n{3,}/);
  });
});
