import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import type { MdcpConfig } from '../config/schema.js';
import { MdcpConfigSchema } from '../config/schema.js';
import type { DocsDetectionResult } from './detect.js';
import { buildDefaultConfig, type InitPreset } from './presets.js';

export function buildAugmentConfig(detection: DocsDetectionResult, preset: InitPreset): MdcpConfig {
  const base = buildDefaultConfig(preset);
  const guides =
    detection.existingGuides.length > 0
      ? detection.existingGuides
      : (base.compileOrder ?? ['glossary', 'features']);

  const compileOrder = guides.includes('glossary')
    ? ['glossary', ...guides.filter((g) => g !== 'glossary')]
    : ['glossary', ...guides];

  return MdcpConfigSchema.parse({
    ...base,
    compileOrder,
    guides: compileOrder.map((name) => ({ name, splitLevel: 2 })),
  });
}

export function writeAdoptionPlan(
  docsRootAbs: string,
  detection: DocsDetectionResult,
  preset: InitPreset,
): { path: string; created: boolean } {
  const planPath = join(docsRootAbs, 'extensions', 'adoption-plan.md');
  mkdirSync(join(docsRootAbs, 'extensions'), { recursive: true });

  const lines = [
    '# MDCP adoption plan',
    '',
    'Generated by `mdcp init --mode augment`. Edit this shard — it is not overwritten on re-run.',
    '',
    `**Preset:** ${preset}`,
    '',
    '## Detected signals',
    '',
    ...detection.signals.map((s) => `- ${s}`),
    '',
    '## Suggested next steps',
    '',
    '1. Add glossary shards under `glossary/` — one term per file.',
    '2. Split large monoliths into topic shards; list them in each guide `index.md`.',
    '3. Run `mdcp compile` and `mdcp check`.',
    '4. Optional: enable `format-*` packs from `spec/extensions/` for C4, worksheets, or ArchiMate templates.',
    '',
  ];

  if (!existsSync(planPath)) {
    writeFileSync(planPath, lines.join('\n'), 'utf-8');
    return { path: planPath, created: true };
  }
  return { path: planPath, created: false };
}

export function writeAugmentConfig(
  docsRootAbs: string,
  config: MdcpConfig,
  dryRun: boolean,
): { path: string; created: boolean } {
  const configPath = join(docsRootAbs, 'mdcp.config.json');
  if (dryRun) return { path: configPath, created: false };
  if (!existsSync(configPath)) {
    writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, 'utf-8');
    return { path: configPath, created: true };
  }
  return { path: configPath, created: false };
}
